### ISSUE TITLE
Stop LE from opening a PDF file on Github launch

### ISSUE THREAD

**Issue by EdSaunders** [oncogenetics/LocusExplorer#13]

**Comment by zx8754** [comment]
@EdSaunders What do you mean?

**Comment by EdSaunders** [comment]
Whenever I run

library(shiny)  
runGitHub("LocusExplorer", "oncogenetics")

it launches the app, but also opens a plot in adobe

**Comment by EdSaunders** [comment]
Think it might be from this part of the ui.R as coordinates of the plot that comes up are chr17_36020000_36140000. Does the example plot part need commenting out? Code starts at line 229.


  tabPanel("Help",
           mainPanel(
             tabsetPanel(
               tabPanel("About",
                        #includeMarkdown("Markdown/HelpAbout.md")
                        includeMarkdown("README.md")),
               tabPanel("Example Plot",
                        h4("PDF"),
                        tags$iframe(src = "chr17_36020000_36140000.pdf",
                                    width="600", height="600")),
               tabPanel("R Session Info",
                        includeMarkdown("Markdown/RSessionInfo.md")),
               tabPanel("LD Tutorial",
                        includeMarkdown("Markdown/LDTutorial.md"))
             )#tabsetPanel
           )#mainPanel
  )#tabPanel - Help
  )#navbarPage
)#shinyUI

**Comment by zx8754** [comment]
@EdSaunders This doesn't happen on Chrome, in any case I will remove PDF example output, and replace it with high res JPEG output.
