### ISSUE TITLE
Error : Aesthetics must either be ...

### ISSUE THREAD

**Issue by AngieHinrichs** [oncogenetics/LocusExplorer#38]
Hi, I have been playing around with LocusExplorer on Mac OS X and in general it's working well but I've noticed that when I try to zoom into a smaller region such as chr2:173330000-173360000 in Plot Settings, instead of the manhattan plot I get this error:

Error : Aesthetics must either be length one, or the same length as the dataProblems:BP, BP, PLog

That also appears in the console output in R.

BTW I'm not seeing the Recombination track -- if it is the only one checked, I see no tracks.  ?

Thanks,
Angie

**Comment by AngieHinrichs** [comment]
Ah, never mind about the Recombination data, I see it is part of the Manhattan plot.

**Comment by zx8754** [comment]
Hi @AngieHinrichs 

Thank you for playing around.

- When zoomed into the region where hit SNP is outside zoomed region, we get an error. It is fixed now.
- Yes, recombination track is part of manhattan, updated the script so it is not possible to select recombination track without Manhattan track selected.

Thanks
Tokhir

**Comment by AngieHinrichs** [comment]
Great, thanks.  The "Manhattan: ..." labeling is also helpful.
