### ISSUE TITLE
Example input data: Please download Histone bigWig files

### ISSUE THREAD

**Issue by AngieHinrichs** [oncogenetics/LocusExplorer#39]
When I use the Example data in Plot Settings, and check all of the tracks, I can see data for all of them except for Histone -- instead of data it has the message "Please download Histone bigWig files!" and I don't see anything about how to incorporate those in the Help tabs.

**Comment by zx8754** [comment]
Hi @AngieHinrichs 

I added *FAQ* panel in *Help* tab.

You can see the *FAQ.md* markdown file [here](https://github.com/oncogenetics/LocusExplorer/blob/master/Markdown/FAQ.md), see question number 5.

Thanks
Tokhir

**Comment by AngieHinrichs** [comment]
Great to see the FAQ.  Yes, the bigWig files are quite large so I can see why you wouldn't want to redistribute them via github!  

I can't tell where runGitHub (http://www.inside-r.org/packages/cran/shiny/docs/runGitHub) puts the local files -- seems not to be in the directory where I'm running R, nor in /tmp -- ha, it appears to be `$TMPDIR/Rtmpzghwdp/shinyapp13e24f209da5/LocusExplorer-master/Data/wgEncodeBroadHistone/`.  (Note: `wgEncodeBroadHistone` not `EncodeBigWig ` as in the FAQ)  Good luck to less persistent github/R n00bs.  :)  Anyway, no rush, but it would be nice to have a note in LocusExplorer/README.md (section Launch Locus Explorer) and/or the FAQ about how to download and run it without runGitHub in order to install the files locally.  (The convenience of runGitHub is great for getting started, though!)

**Comment by AngieHinrichs** [comment]
[FWIW Seems it can't be shoehorned into runGitHub's tmp dir anyway -- it looks like the server needs to see the files when it starts up, but if I runGitHub() again then it will re-download the tar file and make a new tmp dir.  No big deal, LocusExplorer and the files should be installed properly anyway.]

**Comment by zx8754** [comment]
@AngieHinrichs OK, I will add *Download as ZIP* option, so the user knows the location of files, and can add bigwig into right folder. runGitHub() is a quick one, but with limitations, I shall make a note about this in the main README file.
