### ISSUE TITLE
file format: bedGraph not BED

### ISSUE THREAD

**Issue by AngieHinrichs** [oncogenetics/LocusExplorer#40]
The format you're describing is actually bedGraph (http://genome.ucsc.edu/goldenpath/help/bedgraph.html) not BED (http://genome.ucsc.edu/FAQ/FAQformat.html#format1).  The 4th field of BED is a name; the 4th field of bedGraph is a number.

**Comment by zx8754** [comment]
@AngieHinrichs Good point, updated.
