### ISSUE TITLE
R3.7 Suggested filenames with invalid characters

### ISSUE THREAD

**Issue by zx8754** [oncogenetics/LocusExplorer#54]
The suggested filenames when saving a plot contains “ characters at the beginning and end The “ should be removed because not all file systems may handle this appropriately.

**Comment by zx8754** [comment]
Couldn't replicate this bug under Windows, needs testing on OSX

**Comment by zx8754** [comment]
We could not replicate this error.

Tested on:

1. Windows
```R
R version 3.2.2 (2015-08-14)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1
```

2. Mac OS
```R
R version 3.2.2 (2015-08-14)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)
```

Please, suggest re-open this issue with your `sessionInfo()`.

**Comment by EdSaunders** [comment]
Identified that quotation marks are added surrounding the filename when the application is run directly in RStudio. Amended launch instructions and code to use launch.browser = TRUE so that the app is run in an external browser, in which we have not experienced this issue.
